/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.24
 * Generated at: 2019-10-24 20:08:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class bootstrap_002ddemo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("    <meta charset=\"utf-8\">\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("\t<title>Bootstrap Test</title>\n");
      out.write("\n");
      out.write("\t<!-- Latest compiled and minified CSS -->\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\" integrity=\"sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u\" crossorigin=\"anonymous\">\n");
      out.write("\t\n");
      out.write("\t<!-- Optional theme -->\n");
      out.write("\t<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css\" integrity=\"sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp\" crossorigin=\"anonymous\">\n");
      out.write("\t\n");
      out.write("\t<!-- Latest compiled and minified JavaScript -->\n");
      out.write("\t<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\" integrity=\"sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa\" crossorigin=\"anonymous\"></script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("    <!-- Fixed navbar -->\n");
      out.write("    <nav class=\"navbar navbar-inverse navbar-fixed-top\">\n");
      out.write("      <div class=\"container\">\n");
      out.write("        <div class=\"navbar-header\">\n");
      out.write("          <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\" aria-controls=\"navbar\">\n");
      out.write("            <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("            <span class=\"icon-bar\"></span>\n");
      out.write("            <span class=\"icon-bar\"></span>\n");
      out.write("            <span class=\"icon-bar\"></span>\n");
      out.write("          </button>\n");
      out.write("          <a class=\"navbar-brand\" href=\"#\">Bootstrap theme</a>\n");
      out.write("        </div>\n");
      out.write("        <div id=\"navbar\" class=\"navbar-collapse collapse\">\n");
      out.write("          <ul class=\"nav navbar-nav\">\n");
      out.write("            <li class=\"active\"><a href=\"#\">Home</a></li>\n");
      out.write("            <li><a href=\"#about\">About</a></li>\n");
      out.write("            <li><a href=\"#contact\">Contact</a></li>\n");
      out.write("            <li class=\"dropdown\">\n");
      out.write("              <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Dropdown <span class=\"caret\"></span></a>\n");
      out.write("              <ul class=\"dropdown-menu\">\n");
      out.write("                <li><a href=\"#\">Action</a></li>\n");
      out.write("                <li><a href=\"#\">Another action</a></li>\n");
      out.write("                <li><a href=\"#\">Something else here</a></li>\n");
      out.write("                <li role=\"separator\" class=\"divider\"></li>\n");
      out.write("                <li class=\"dropdown-header\">Nav header</li>\n");
      out.write("                <li><a href=\"#\">Separated link</a></li>\n");
      out.write("                <li><a href=\"#\">One more separated link</a></li>\n");
      out.write("              </ul>\n");
      out.write("            </li>\n");
      out.write("          </ul>\n");
      out.write("        </div><!--/.nav-collapse -->\n");
      out.write("      </div>\n");
      out.write("    </nav>\n");
      out.write("\n");
      out.write("    <div class=\"container theme-showcase\" role=\"main\">\n");
      out.write("\n");
      out.write("      <!-- Main jumbotron for a primary marketing message or call to action -->\n");
      out.write("      <div class=\"jumbotron\">\n");
      out.write("        <h1>Theme example</h1>\n");
      out.write("        <p>This is a template showcasing the optional theme stylesheet included in Bootstrap. Use it as a starting point to create something more unique by building on or modifying it.</p>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("      <div class=\"page-header\">\n");
      out.write("        <h1>Buttons</h1>\n");
      out.write("      </div>\n");
      out.write("      <p>\n");
      out.write("        <button type=\"button\" class=\"btn btn-lg btn-default\">Default</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-lg btn-primary\">Primary</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-lg btn-success\">Success</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-lg btn-info\">Info</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-lg btn-warning\">Warning</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-lg btn-danger\">Danger</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-lg btn-link\">Link</button>\n");
      out.write("      </p>\n");
      out.write("      <p>\n");
      out.write("        <button type=\"button\" class=\"btn btn-default\">Default</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-primary\">Primary</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-success\">Success</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-info\">Info</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-warning\">Warning</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-danger\">Danger</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-link\">Link</button>\n");
      out.write("      </p>\n");
      out.write("      <p>\n");
      out.write("        <button type=\"button\" class=\"btn btn-sm btn-default\">Default</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-sm btn-primary\">Primary</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-sm btn-success\">Success</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-sm btn-info\">Info</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-sm btn-warning\">Warning</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-sm btn-danger\">Danger</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-sm btn-link\">Link</button>\n");
      out.write("      </p>\n");
      out.write("      <p>\n");
      out.write("        <button type=\"button\" class=\"btn btn-xs btn-default\">Default</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-xs btn-primary\">Primary</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-xs btn-success\">Success</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-xs btn-info\">Info</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-xs btn-warning\">Warning</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-xs btn-danger\">Danger</button>\n");
      out.write("        <button type=\"button\" class=\"btn btn-xs btn-link\">Link</button>\n");
      out.write("      </p>\n");
      out.write("\n");
      out.write("\n");
      out.write("      <div class=\"page-header\">\n");
      out.write("        <h1>Tables</h1>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-md-6\">\n");
      out.write("          <table class=\"table\">\n");
      out.write("            <thead>\n");
      out.write("              <tr>\n");
      out.write("                <th>#</th>\n");
      out.write("                <th>First Name</th>\n");
      out.write("                <th>Last Name</th>\n");
      out.write("                <th>Username</th>\n");
      out.write("              </tr>\n");
      out.write("            </thead>\n");
      out.write("            <tbody>\n");
      out.write("              <tr>\n");
      out.write("                <td>1</td>\n");
      out.write("                <td>Mark</td>\n");
      out.write("                <td>Otto</td>\n");
      out.write("                <td>@mdo</td>\n");
      out.write("              </tr>\n");
      out.write("              <tr>\n");
      out.write("                <td>2</td>\n");
      out.write("                <td>Jacob</td>\n");
      out.write("                <td>Thornton</td>\n");
      out.write("                <td>@fat</td>\n");
      out.write("              </tr>\n");
      out.write("              <tr>\n");
      out.write("                <td>3</td>\n");
      out.write("                <td>Larry</td>\n");
      out.write("                <td>the Bird</td>\n");
      out.write("                <td>@twitter</td>\n");
      out.write("              </tr>\n");
      out.write("            </tbody>\n");
      out.write("          </table>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-6\">\n");
      out.write("          <table class=\"table table-striped\">\n");
      out.write("            <thead>\n");
      out.write("              <tr>\n");
      out.write("                <th>#</th>\n");
      out.write("                <th>First Name</th>\n");
      out.write("                <th>Last Name</th>\n");
      out.write("                <th>Username</th>\n");
      out.write("              </tr>\n");
      out.write("            </thead>\n");
      out.write("            <tbody>\n");
      out.write("              <tr>\n");
      out.write("                <td>1</td>\n");
      out.write("                <td>Mark</td>\n");
      out.write("                <td>Otto</td>\n");
      out.write("                <td>@mdo</td>\n");
      out.write("              </tr>\n");
      out.write("              <tr>\n");
      out.write("                <td>2</td>\n");
      out.write("                <td>Jacob</td>\n");
      out.write("                <td>Thornton</td>\n");
      out.write("                <td>@fat</td>\n");
      out.write("              </tr>\n");
      out.write("              <tr>\n");
      out.write("                <td>3</td>\n");
      out.write("                <td>Larry</td>\n");
      out.write("                <td>the Bird</td>\n");
      out.write("                <td>@twitter</td>\n");
      out.write("              </tr>\n");
      out.write("            </tbody>\n");
      out.write("          </table>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-md-6\">\n");
      out.write("          <table class=\"table table-bordered\">\n");
      out.write("            <thead>\n");
      out.write("              <tr>\n");
      out.write("                <th>#</th>\n");
      out.write("                <th>First Name</th>\n");
      out.write("                <th>Last Name</th>\n");
      out.write("                <th>Username</th>\n");
      out.write("              </tr>\n");
      out.write("            </thead>\n");
      out.write("            <tbody>\n");
      out.write("              <tr>\n");
      out.write("                <td rowspan=\"2\">1</td>\n");
      out.write("                <td>Mark</td>\n");
      out.write("                <td>Otto</td>\n");
      out.write("                <td>@mdo</td>\n");
      out.write("              </tr>\n");
      out.write("              <tr>\n");
      out.write("                <td>Mark</td>\n");
      out.write("                <td>Otto</td>\n");
      out.write("                <td>@TwBootstrap</td>\n");
      out.write("              </tr>\n");
      out.write("              <tr>\n");
      out.write("                <td>2</td>\n");
      out.write("                <td>Jacob</td>\n");
      out.write("                <td>Thornton</td>\n");
      out.write("                <td>@fat</td>\n");
      out.write("              </tr>\n");
      out.write("              <tr>\n");
      out.write("                <td>3</td>\n");
      out.write("                <td colspan=\"2\">Larry the Bird</td>\n");
      out.write("                <td>@twitter</td>\n");
      out.write("              </tr>\n");
      out.write("            </tbody>\n");
      out.write("          </table>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"col-md-6\">\n");
      out.write("          <table class=\"table table-condensed\">\n");
      out.write("            <thead>\n");
      out.write("              <tr>\n");
      out.write("                <th>#</th>\n");
      out.write("                <th>First Name</th>\n");
      out.write("                <th>Last Name</th>\n");
      out.write("                <th>Username</th>\n");
      out.write("              </tr>\n");
      out.write("            </thead>\n");
      out.write("            <tbody>\n");
      out.write("              <tr>\n");
      out.write("                <td>1</td>\n");
      out.write("                <td>Mark</td>\n");
      out.write("                <td>Otto</td>\n");
      out.write("                <td>@mdo</td>\n");
      out.write("              </tr>\n");
      out.write("              <tr>\n");
      out.write("                <td>2</td>\n");
      out.write("                <td>Jacob</td>\n");
      out.write("                <td>Thornton</td>\n");
      out.write("                <td>@fat</td>\n");
      out.write("              </tr>\n");
      out.write("              <tr>\n");
      out.write("                <td>3</td>\n");
      out.write("                <td colspan=\"2\">Larry the Bird</td>\n");
      out.write("                <td>@twitter</td>\n");
      out.write("              </tr>\n");
      out.write("            </tbody>\n");
      out.write("          </table>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("      <div class=\"page-header\">\n");
      out.write("        <h1>Thumbnails</h1>\n");
      out.write("      </div>\n");
      out.write("      <img data-src=\"holder.js/200x200\" class=\"img-thumbnail\" alt=\"A generic square placeholder image with a white border around it, making it resemble a photograph taken with an old instant camera\">\n");
      out.write("\n");
      out.write("\n");
      out.write("      <div class=\"page-header\">\n");
      out.write("        <h1>Labels</h1>\n");
      out.write("      </div>\n");
      out.write("      <h1>\n");
      out.write("        <span class=\"label label-default\">Default</span>\n");
      out.write("        <span class=\"label label-primary\">Primary</span>\n");
      out.write("        <span class=\"label label-success\">Success</span>\n");
      out.write("        <span class=\"label label-info\">Info</span>\n");
      out.write("        <span class=\"label label-warning\">Warning</span>\n");
      out.write("        <span class=\"label label-danger\">Danger</span>\n");
      out.write("      </h1>\n");
      out.write("      <h2>\n");
      out.write("        <span class=\"label label-default\">Default</span>\n");
      out.write("        <span class=\"label label-primary\">Primary</span>\n");
      out.write("        <span class=\"label label-success\">Success</span>\n");
      out.write("        <span class=\"label label-info\">Info</span>\n");
      out.write("        <span class=\"label label-warning\">Warning</span>\n");
      out.write("        <span class=\"label label-danger\">Danger</span>\n");
      out.write("      </h2>\n");
      out.write("      <h3>\n");
      out.write("        <span class=\"label label-default\">Default</span>\n");
      out.write("        <span class=\"label label-primary\">Primary</span>\n");
      out.write("        <span class=\"label label-success\">Success</span>\n");
      out.write("        <span class=\"label label-info\">Info</span>\n");
      out.write("        <span class=\"label label-warning\">Warning</span>\n");
      out.write("        <span class=\"label label-danger\">Danger</span>\n");
      out.write("      </h3>\n");
      out.write("      <h4>\n");
      out.write("        <span class=\"label label-default\">Default</span>\n");
      out.write("        <span class=\"label label-primary\">Primary</span>\n");
      out.write("        <span class=\"label label-success\">Success</span>\n");
      out.write("        <span class=\"label label-info\">Info</span>\n");
      out.write("        <span class=\"label label-warning\">Warning</span>\n");
      out.write("        <span class=\"label label-danger\">Danger</span>\n");
      out.write("      </h4>\n");
      out.write("      <h5>\n");
      out.write("        <span class=\"label label-default\">Default</span>\n");
      out.write("        <span class=\"label label-primary\">Primary</span>\n");
      out.write("        <span class=\"label label-success\">Success</span>\n");
      out.write("        <span class=\"label label-info\">Info</span>\n");
      out.write("        <span class=\"label label-warning\">Warning</span>\n");
      out.write("        <span class=\"label label-danger\">Danger</span>\n");
      out.write("      </h5>\n");
      out.write("      <h6>\n");
      out.write("        <span class=\"label label-default\">Default</span>\n");
      out.write("        <span class=\"label label-primary\">Primary</span>\n");
      out.write("        <span class=\"label label-success\">Success</span>\n");
      out.write("        <span class=\"label label-info\">Info</span>\n");
      out.write("        <span class=\"label label-warning\">Warning</span>\n");
      out.write("        <span class=\"label label-danger\">Danger</span>\n");
      out.write("      </h6>\n");
      out.write("      <p>\n");
      out.write("        <span class=\"label label-default\">Default</span>\n");
      out.write("        <span class=\"label label-primary\">Primary</span>\n");
      out.write("        <span class=\"label label-success\">Success</span>\n");
      out.write("        <span class=\"label label-info\">Info</span>\n");
      out.write("        <span class=\"label label-warning\">Warning</span>\n");
      out.write("        <span class=\"label label-danger\">Danger</span>\n");
      out.write("      </p>\n");
      out.write("\n");
      out.write("\n");
      out.write("      <div class=\"page-header\">\n");
      out.write("        <h1>Badges</h1>\n");
      out.write("      </div>\n");
      out.write("      <p>\n");
      out.write("        <a href=\"#\">Inbox <span class=\"badge\">42</span></a>\n");
      out.write("      </p>\n");
      out.write("      <ul class=\"nav nav-pills\" role=\"tablist\">\n");
      out.write("        <li role=\"presentation\" class=\"active\"><a href=\"#\">Home <span class=\"badge\">42</span></a></li>\n");
      out.write("        <li role=\"presentation\"><a href=\"#\">Profile</a></li>\n");
      out.write("        <li role=\"presentation\"><a href=\"#\">Messages <span class=\"badge\">3</span></a></li>\n");
      out.write("      </ul>\n");
      out.write("\n");
      out.write("\n");
      out.write("      <div class=\"page-header\">\n");
      out.write("        <h1>Dropdown menus</h1>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"dropdown theme-dropdown clearfix\">\n");
      out.write("        <a id=\"dropdownMenu1\" href=\"#\" class=\"sr-only dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Dropdown <span class=\"caret\"></span></a>\n");
      out.write("        <ul class=\"dropdown-menu\" aria-labelledby=\"dropdownMenu1\">\n");
      out.write("          <li class=\"active\"><a href=\"#\">Action</a></li>\n");
      out.write("          <li><a href=\"#\">Another action</a></li>\n");
      out.write("          <li><a href=\"#\">Something else here</a></li>\n");
      out.write("          <li role=\"separator\" class=\"divider\"></li>\n");
      out.write("          <li><a href=\"#\">Separated link</a></li>\n");
      out.write("        </ul>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("      <div class=\"page-header\">\n");
      out.write("        <h1>Navs</h1>\n");
      out.write("      </div>\n");
      out.write("      <ul class=\"nav nav-tabs\" role=\"tablist\">\n");
      out.write("        <li role=\"presentation\" class=\"active\"><a href=\"#\">Home</a></li>\n");
      out.write("        <li role=\"presentation\"><a href=\"#\">Profile</a></li>\n");
      out.write("        <li role=\"presentation\"><a href=\"#\">Messages</a></li>\n");
      out.write("      </ul>\n");
      out.write("      <ul class=\"nav nav-pills\" role=\"tablist\">\n");
      out.write("        <li role=\"presentation\" class=\"active\"><a href=\"#\">Home</a></li>\n");
      out.write("        <li role=\"presentation\"><a href=\"#\">Profile</a></li>\n");
      out.write("        <li role=\"presentation\"><a href=\"#\">Messages</a></li>\n");
      out.write("      </ul>\n");
      out.write("\n");
      out.write("\n");
      out.write("      <div class=\"page-header\">\n");
      out.write("        <h1>Navbars</h1>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("      <nav class=\"navbar navbar-default\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("          <div class=\"navbar-header\">\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\n");
      out.write("              <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("              <span class=\"icon-bar\"></span>\n");
      out.write("              <span class=\"icon-bar\"></span>\n");
      out.write("              <span class=\"icon-bar\"></span>\n");
      out.write("            </button>\n");
      out.write("            <a class=\"navbar-brand\" href=\"#\">Project name</a>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"navbar-collapse collapse\">\n");
      out.write("            <ul class=\"nav navbar-nav\">\n");
      out.write("              <li class=\"active\"><a href=\"#\">Home</a></li>\n");
      out.write("              <li><a href=\"#about\">About</a></li>\n");
      out.write("              <li><a href=\"#contact\">Contact</a></li>\n");
      out.write("              <li class=\"dropdown\">\n");
      out.write("                <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Dropdown <span class=\"caret\"></span></a>\n");
      out.write("                <ul class=\"dropdown-menu\">\n");
      out.write("                  <li><a href=\"#\">Action</a></li>\n");
      out.write("                  <li><a href=\"#\">Another action</a></li>\n");
      out.write("                  <li><a href=\"#\">Something else here</a></li>\n");
      out.write("                  <li role=\"separator\" class=\"divider\"></li>\n");
      out.write("                  <li class=\"dropdown-header\">Nav header</li>\n");
      out.write("                  <li><a href=\"#\">Separated link</a></li>\n");
      out.write("                  <li><a href=\"#\">One more separated link</a></li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("            </ul>\n");
      out.write("          </div><!--/.nav-collapse -->\n");
      out.write("        </div>\n");
      out.write("      </nav>\n");
      out.write("\n");
      out.write("      <nav class=\"navbar navbar-inverse\">\n");
      out.write("        <div class=\"container\">\n");
      out.write("          <div class=\"navbar-header\">\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle collapsed\" data-toggle=\"collapse\" data-target=\".navbar-collapse\">\n");
      out.write("              <span class=\"sr-only\">Toggle navigation</span>\n");
      out.write("              <span class=\"icon-bar\"></span>\n");
      out.write("              <span class=\"icon-bar\"></span>\n");
      out.write("              <span class=\"icon-bar\"></span>\n");
      out.write("            </button>\n");
      out.write("            <a class=\"navbar-brand\" href=\"#\">Project name</a>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"navbar-collapse collapse\">\n");
      out.write("            <ul class=\"nav navbar-nav\">\n");
      out.write("              <li class=\"active\"><a href=\"#\">Home</a></li>\n");
      out.write("              <li><a href=\"#about\">About</a></li>\n");
      out.write("              <li><a href=\"#contact\">Contact</a></li>\n");
      out.write("              <li class=\"dropdown\">\n");
      out.write("                <a href=\"#\" class=\"dropdown-toggle\" data-toggle=\"dropdown\" role=\"button\" aria-haspopup=\"true\" aria-expanded=\"false\">Dropdown <span class=\"caret\"></span></a>\n");
      out.write("                <ul class=\"dropdown-menu\">\n");
      out.write("                  <li><a href=\"#\">Action</a></li>\n");
      out.write("                  <li><a href=\"#\">Another action</a></li>\n");
      out.write("                  <li><a href=\"#\">Something else here</a></li>\n");
      out.write("                  <li role=\"separator\" class=\"divider\"></li>\n");
      out.write("                  <li class=\"dropdown-header\">Nav header</li>\n");
      out.write("                  <li><a href=\"#\">Separated link</a></li>\n");
      out.write("                  <li><a href=\"#\">One more separated link</a></li>\n");
      out.write("                </ul>\n");
      out.write("              </li>\n");
      out.write("            </ul>\n");
      out.write("          </div><!--/.nav-collapse -->\n");
      out.write("        </div>\n");
      out.write("      </nav>\n");
      out.write("\n");
      out.write("\n");
      out.write("      <div class=\"page-header\">\n");
      out.write("        <h1>Alerts</h1>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"alert alert-success\" role=\"alert\">\n");
      out.write("        <strong>Well done!</strong> You successfully read this important alert message.\n");
      out.write("      </div>\n");
      out.write("      <div class=\"alert alert-info\" role=\"alert\">\n");
      out.write("        <strong>Heads up!</strong> This alert needs your attention, but it's not super important.\n");
      out.write("      </div>\n");
      out.write("      <div class=\"alert alert-warning\" role=\"alert\">\n");
      out.write("        <strong>Warning!</strong> Best check yo self, you're not looking too good.\n");
      out.write("      </div>\n");
      out.write("      <div class=\"alert alert-danger\" role=\"alert\">\n");
      out.write("        <strong>Oh snap!</strong> Change a few things up and try submitting again.\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("      <div class=\"page-header\">\n");
      out.write("        <h1>Progress bars</h1>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"progress\">\n");
      out.write("        <div class=\"progress-bar\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 60%;\"><span class=\"sr-only\">60% Complete</span></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"progress\">\n");
      out.write("        <div class=\"progress-bar progress-bar-success\" role=\"progressbar\" aria-valuenow=\"40\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 40%\"><span class=\"sr-only\">40% Complete (success)</span></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"progress\">\n");
      out.write("        <div class=\"progress-bar progress-bar-info\" role=\"progressbar\" aria-valuenow=\"20\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 20%\"><span class=\"sr-only\">20% Complete</span></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"progress\">\n");
      out.write("        <div class=\"progress-bar progress-bar-warning\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 60%\"><span class=\"sr-only\">60% Complete (warning)</span></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"progress\">\n");
      out.write("        <div class=\"progress-bar progress-bar-danger\" role=\"progressbar\" aria-valuenow=\"80\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 80%\"><span class=\"sr-only\">80% Complete (danger)</span></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"progress\">\n");
      out.write("        <div class=\"progress-bar progress-bar-striped\" role=\"progressbar\" aria-valuenow=\"60\" aria-valuemin=\"0\" aria-valuemax=\"100\" style=\"width: 60%\"><span class=\"sr-only\">60% Complete</span></div>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"progress\">\n");
      out.write("        <div class=\"progress-bar progress-bar-success\" style=\"width: 35%\"><span class=\"sr-only\">35% Complete (success)</span></div>\n");
      out.write("        <div class=\"progress-bar progress-bar-warning\" style=\"width: 20%\"><span class=\"sr-only\">20% Complete (warning)</span></div>\n");
      out.write("        <div class=\"progress-bar progress-bar-danger\" style=\"width: 10%\"><span class=\"sr-only\">10% Complete (danger)</span></div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("      <div class=\"page-header\">\n");
      out.write("        <h1>List groups</h1>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-sm-4\">\n");
      out.write("          <ul class=\"list-group\">\n");
      out.write("            <li class=\"list-group-item\">Cras justo odio</li>\n");
      out.write("            <li class=\"list-group-item\">Dapibus ac facilisis in</li>\n");
      out.write("            <li class=\"list-group-item\">Morbi leo risus</li>\n");
      out.write("            <li class=\"list-group-item\">Porta ac consectetur ac</li>\n");
      out.write("            <li class=\"list-group-item\">Vestibulum at eros</li>\n");
      out.write("          </ul>\n");
      out.write("        </div><!-- /.col-sm-4 -->\n");
      out.write("        <div class=\"col-sm-4\">\n");
      out.write("          <div class=\"list-group\">\n");
      out.write("            <a href=\"#\" class=\"list-group-item active\">\n");
      out.write("              Cras justo odio\n");
      out.write("            </a>\n");
      out.write("            <a href=\"#\" class=\"list-group-item\">Dapibus ac facilisis in</a>\n");
      out.write("            <a href=\"#\" class=\"list-group-item\">Morbi leo risus</a>\n");
      out.write("            <a href=\"#\" class=\"list-group-item\">Porta ac consectetur ac</a>\n");
      out.write("            <a href=\"#\" class=\"list-group-item\">Vestibulum at eros</a>\n");
      out.write("          </div>\n");
      out.write("        </div><!-- /.col-sm-4 -->\n");
      out.write("        <div class=\"col-sm-4\">\n");
      out.write("          <div class=\"list-group\">\n");
      out.write("            <a href=\"#\" class=\"list-group-item active\">\n");
      out.write("              <h4 class=\"list-group-item-heading\">List group item heading</h4>\n");
      out.write("              <p class=\"list-group-item-text\">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>\n");
      out.write("            </a>\n");
      out.write("            <a href=\"#\" class=\"list-group-item\">\n");
      out.write("              <h4 class=\"list-group-item-heading\">List group item heading</h4>\n");
      out.write("              <p class=\"list-group-item-text\">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>\n");
      out.write("            </a>\n");
      out.write("            <a href=\"#\" class=\"list-group-item\">\n");
      out.write("              <h4 class=\"list-group-item-heading\">List group item heading</h4>\n");
      out.write("              <p class=\"list-group-item-text\">Donec id elit non mi porta gravida at eget metus. Maecenas sed diam eget risus varius blandit.</p>\n");
      out.write("            </a>\n");
      out.write("          </div>\n");
      out.write("        </div><!-- /.col-sm-4 -->\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("      <div class=\"page-header\">\n");
      out.write("        <h1>Panels</h1>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"row\">\n");
      out.write("        <div class=\"col-sm-4\">\n");
      out.write("          <div class=\"panel panel-default\">\n");
      out.write("            <div class=\"panel-heading\">\n");
      out.write("              <h3 class=\"panel-title\">Panel title</h3>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"panel-body\">\n");
      out.write("              Panel content\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"panel panel-primary\">\n");
      out.write("            <div class=\"panel-heading\">\n");
      out.write("              <h3 class=\"panel-title\">Panel title</h3>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"panel-body\">\n");
      out.write("              Panel content\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div><!-- /.col-sm-4 -->\n");
      out.write("        <div class=\"col-sm-4\">\n");
      out.write("          <div class=\"panel panel-success\">\n");
      out.write("            <div class=\"panel-heading\">\n");
      out.write("              <h3 class=\"panel-title\">Panel title</h3>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"panel-body\">\n");
      out.write("              Panel content\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"panel panel-info\">\n");
      out.write("            <div class=\"panel-heading\">\n");
      out.write("              <h3 class=\"panel-title\">Panel title</h3>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"panel-body\">\n");
      out.write("              Panel content\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div><!-- /.col-sm-4 -->\n");
      out.write("        <div class=\"col-sm-4\">\n");
      out.write("          <div class=\"panel panel-warning\">\n");
      out.write("            <div class=\"panel-heading\">\n");
      out.write("              <h3 class=\"panel-title\">Panel title</h3>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"panel-body\">\n");
      out.write("              Panel content\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("          <div class=\"panel panel-danger\">\n");
      out.write("            <div class=\"panel-heading\">\n");
      out.write("              <h3 class=\"panel-title\">Panel title</h3>\n");
      out.write("            </div>\n");
      out.write("            <div class=\"panel-body\">\n");
      out.write("              Panel content\n");
      out.write("            </div>\n");
      out.write("          </div>\n");
      out.write("        </div><!-- /.col-sm-4 -->\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("      <div class=\"page-header\">\n");
      out.write("        <h1>Wells</h1>\n");
      out.write("      </div>\n");
      out.write("      <div class=\"well\">\n");
      out.write("        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas sed diam eget risus varius blandit sit amet non magna. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Cras mattis consectetur purus sit amet fermentum. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit. Aenean lacinia bibendum nulla sed consectetur.</p>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("    </div> <!-- /container -->\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
